# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run the gemspec command
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = %q{metamorphosis}
  s.version = "0.1.0"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jean-Denis Vauguet"]
  s.date = %q{2010-03-25}
  s.description = %q{Metamorphosis is a generic plugins system. Using Metamorphosis, a module or a class is able to alter and/or extend its original behavior at will.}
  s.email = %q{jd@vauguet.fr}
  s.extra_rdoc_files = [
    "LICENSE",
     "README.md",
     "TODO"
  ]
  s.files = [
    ".document",
     ".gitignore",
     ".yardopts",
     "LICENSE",
     "README.md",
     "Rakefile",
     "TODO",
     "VERSION",
     "example/spells/backward.rb",
     "example/spells/loudness.rb",
     "example/test_metamorphosis.rb",
     "lib/ext/ext.rb",
     "lib/metamorphosis.rb",
     "lib/metamorphosis/core.rb",
     "lib/metamorphosis/helpers.rb",
     "metamorphosis.gemspec"
  ]
  s.homepage = %q{http://github.com/chikamichi/metamorphosis}
  s.rdoc_options = ["--charset=UTF-8"]
  s.require_paths = ["lib"]
  s.rubygems_version = %q{1.3.6}
  s.summary = %q{A generic plugin system. Let's do some differentiation!}

  if s.respond_to? :specification_version then
    current_version = Gem::Specification::CURRENT_SPECIFICATION_VERSION
    s.specification_version = 3

    if Gem::Version.new(Gem::RubyGemsVersion) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<configliere>, [">= 0.0.5"])
      s.add_runtime_dependency(%q<activesupport>, [">= 0"])
    else
      s.add_dependency(%q<configliere>, [">= 0.0.5"])
      s.add_dependency(%q<activesupport>, [">= 0"])
    end
  else
    s.add_dependency(%q<configliere>, [">= 0.0.5"])
    s.add_dependency(%q<activesupport>, [">= 0"])
  end
end

